### ISSUE TITLE
STS lacks simple terminal emulation.

### ISSUE THREAD

**Issue by sam-falvo** [KestrelComputer/kestrel#167]
Necessary to support interactive use of STS via the emulated bitmapped display.  Also required for Milestone-2.

**Comment by sam-falvo** [comment]
`/dev/term/control` can be used to control aspects of the display.  It can be read to get the current terminal size as well.  Message-oriented, command/request protocol.

`/dev/term/stream` is the actual byte stream, write-only.  You can reposition the cursor by seeking on this file.

**Comment by larsbrinkhoff** [comment]
Unrelated; will your presentation about RISC V testing appear online?

**Comment by sam-falvo** [comment]
Yes!  We stream live to Youtube.  But, there's no guarantee on quality,
since we lack professional equipment.  Glitches happen more frequently than
we like.

I'll let you know where to find the presentation once it's up.

**Comment by larsbrinkhoff** [comment]
Thanks!

**Comment by sam-falvo** [comment]
Here's the link to the morning session, where I give my presentation: https://www.youtube.com/watch?v=0u2_jKfo0A8

**Comment by larsbrinkhoff** [comment]
Thank you!

**Comment by sam-falvo** [comment]
Split into #180 and #181.  Also, unsure about Plan-9-like files to control terminal emulation.  I thought it'd be simpler to implement, but complexity is dominated by framebuffer and cursor management code.  FS interface can be layered on top after TYPE and EMIT support the MGIA natively.
