### ISSUE TITLE
'e' emulator should have a headless option to facilitate Travis-based CI.

### ISSUE THREAD

**Issue by sam-falvo** [KestrelComputer/kestrel#252]

**Comment by neuschaefer** [comment]
A few ideas:
- `BYE` or a different forth word could turn off the interpreter (see also src/e/processor.c, `do_hostif`)
- Running the forth interpreter with UART input/output may also be useful on hardware, and I think the same firmware should run on hardware and in _e_.
- The "stdio" device could be selected through a GPIO pin that's read when Forth starts. This pin could can simulated in _e_ (obviously), and hooked up to a jumper header or DIP switch on hardware. This is a simple configuration mechanism, but won't scale to many bits of configuration.

**Comment by sam-falvo** [comment]
No longer relevant; new computer specification is already headless (uses serial port for communication with outside world), so 'e' no longer represents a real machine.
